### ISSUE TITLE
Still can't get local ID and device ID

### ISSUE THREAD

**Issue by treforparr** [joshstrange/eufy-robovac#9] opened 2020-07-30 23:09 UTC
Tried everything to get it working with hoobs and HomeBridge I tried everything with a virtual PC and android and I still can't get the local ID I've tried the app for eufy app if anybody can help please in between the appreciated

**Comment by apexad** [comment] 2020-08-01 23:00
Duplicate of #8

**Closed by apexad** 2020-08-01 23:00 UTC
